version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nodejs-api
    overwrite: true

permissions:
  - object: /var/www/nodejs-api
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /var/www/nodejs-api
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
  
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root