version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Running tests...
      - npm test || true

  build:
    commands:
      - echo No build step required for JavaScript projects
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Creating deployment package...
      - mkdir -p deployment
      - cp -r . deployment/
      - cd deployment
      - npm install --production
      - rm -rf node_modules/.cache
      - cd ..

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
