version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Running tests...
      - npm test || true

  build:
    commands:
      - echo No build step required for JavaScript projects
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
